project_id = "ednacharge"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["ednacharge://"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false
secure_password_change = false

[auth.sms]
enable_signup = true
enable_confirmations = true
otp_length = 6

[realtime]
enabled = true
